rule R01_clean_and_remove_naive_duplicates:
    input:
        script="src/scripts/S101_clean_and_remove_naive_duplicates.py"
    output:
        parquet="data/R01_clean_and_remove_naive_duplicates/remaining_data_source_names.parquet"
    log:
        "logs/R01_clean_and_remove_naive_duplicates.log"
    shell:
        """
        python {input.script} \
            --output_parquet {output.parquet} \
            2>&1 | tee {log}
        """


rule R02_build_clusters_of_registries:
    input:
        script="src/scripts/S201_embed_data_source_names_MistralEmbed.py",
        remaining_data_source_names="data/R01_clean_and_remove_naive_duplicates/remaining_data_source_names.parquet"
    output:
        embeddings_all="data/R02_embed_publications_MistralEmbed/Mistral_embeddings.parquet",
        embeddings_sampled="data/R02_embed_publications_MistralEmbed/Mistral_embeddings_sample.parquet"
    log:
        "logs/R02_embed_publications_MistralEmbed.log"
    shell:
        """
        python {input.script} \
            --remaining_data_source_names {input.remaining_data_source_names} \
            --embeddings_all {output.embeddings_all} \
            --embeddings_sampled {output.embeddings_sampled} \
            2>&1 | tee {log}
        """

rule R03_build_empirical_clusters_on_sample_dataset:
    input:
        script="src/scripts/S301_build_empirical_clusters_on_sample_dataset.py",
        # embeddings_sampled="data/R02_embed_publications_MistralEmbed/Mistral_embeddings_sample.parquet"
        embeddings_sampled="../../datasets/003_embeddings_of_registry_names_dataset/Mistral_embeddings_sample.parquet"
    output:
        clusters_parquet="data/R03_build_empirical_clusters_on_sample_dataset/clusters.parquet"
    log:
        "logs/R03_build_empirical_clusters_on_sample_dataset.log"
    shell:
        """
        python {input.script} \
            --embeddings_sampled {input.embeddings_sampled} \
            --clusters_parquet {output.clusters_parquet} \
            2>&1 | tee {log}
        """

rule R04_eval_dataset_build_pairs_from_empirical_custers:
    input:
        script="src/scripts/S401_eval_dataset_build_pairs_from_empirical_custers.py",
        clusters_parquet="data/R03_build_empirical_clusters_on_sample_dataset/clusters.parquet"
    output:
        pairs_parquet="data/R04_eval_dataset_build_pairs_from_empirical_custers/pairs.parquet"
    log:
        "logs/R04_eval_dataset_build_pairs_from_empirical_custers.log"
    shell:
        """
        python {input.script} \
            --clusters_parquet {input.clusters_parquet} \
            --pairs_parquet {output.pairs_parquet} \
            2>&1 | tee {log}
        """

rule R05_eval_dataset_refine_pairs_with_llm:
    input:
        script="src/scripts/S501_eval_dataset_refine_pairs_with_llm.py",
        prompt="etc/prompts/prompt_pairing_assigment_v2.txt",
        pairs_parquet="data/R04_eval_dataset_build_pairs_from_empirical_custers/pairs.parquet"
    output:
        refined_evaluation_dataset="data/R05_eval_dataset_refine_pairs_with_llm/refined_pairs.parquet"
        track_category_switches="data/R05_eval_dataset_refine_pairs_with_llm/track_category_switches.parquet"
    log:
        "logs/R501_eval_dataset_refine_pairs_with_llm.log"
    shell:
        """
        python {input.script} \
            --pairs_parquet {input.pairs_parquet} \
            --prompt {input.prompt} \
            --output_eval_dataset {output.refined_pairs_parquet} \
            --output_track_category_switches {output.track_category_switches} \
            2>&1 | tee {log}
        """
        
rule R06_exps_w_training_of_clustering_model:
    input:
        script="src/scripts/S601_exps_w_training_of_clustering_model.py",
        training_dataset="../../datasets/003_embeddings_of_registry_names_dataset/Mistral_embeddings.parquet",
        evaluation_dataset="../../datasets/004_registry_names_deduplication_eval_dataset/evaluation_dataset.parquet",
    output:
        directory("data/R06_exps_w_training_of_clustering_model"),
    log:
        "logs/R06_exps_w_training_of_clustering_model.log"
    shell:
        """
        python {input.script} \
            --training_dataset {input.training_dataset} \
            --evaluation_dataset {input.evaluation_dataset} \
            --output_dir {output} \
            2>&1 | tee {log}
        """

rule R07_find_best_clustering_model_w_grid_search:
    input:
        script="src/scripts/S602_find_best_clustering_model_w_grid_search.py",
        training_dataset="../../datasets/003_embeddings_of_registry_names_dataset/Mistral_embeddings.parquet",
        evaluation_dataset="../../datasets/004_registry_names_deduplication_eval_dataset/evaluation_dataset.parquet",
    output:
        directory("data/R07_find_best_clustering_model_w_grid_search"),
    log:
        "logs/R07_find_best_clustering_model_w_grid_search.log"
    shell:
        """
        python {input.script} \
            --training_dataset {input.training_dataset} \
            --evaluation_dataset {input.evaluation_dataset} \
            --output_dir {output} \
            2>&1 | tee {log}
        """

rule R08_build_clusters_w_best_params_on_all_data:
    input:
        script="src/scripts/S701_build_clusters_w_best_params_on_all_data.py",
        data_source_names_embeddings_all="../../datasets/002_embeddings_of_registry_names_dataset/Mistral_embeddings.parquet",
    output:
        clusters_parquet="data/R08_build_clusters_w_best_params_on_all_data/clusters.parquet",
    log:
        "logs/R08_build_clusters_w_best_params_on_all_data.log"
    shell:
        """
        python {input.script} \
            --data_source_names_embeddings_all {input.data_source_names_embeddings_all} \
            --clusters_parquet {output.clusters_parquet} \
            2>&1 | tee {log}
        """